/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all, std.string, std.file, std.c.windows.windows, std.conv, jpg, imageprocessor;

class FileItem
{
	this(string fname)
	{
		fullname = fname;
		auto i = fname.lastIndexOf('\\');
		name = fname[i+1..$];
	}

	string toString() const
	{
		return name;
	}

	string fullname, name;
}

class MainForm : dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.button.Button btnBrowse;
	dfl.button.Button btnSave;
	dfl.textbox.TextBox txtOutFile;
	dfl.label.Label label1;
	dfl.label.Label label2;
	dfl.textbox.TextBox txtWidth;
	dfl.label.Label label3;
	dfl.textbox.TextBox txtHeight;
	dfl.listbox.ListBox lbxFiles;
	dfl.picturebox.PictureBox picBox;
	//~Entice Designer variables end here.	
	
	this()
	{
		jpgWriter = new JpegWriter;
		imgProc = new ImageProcessor(&onGotThumb);
		initializeMyForm();		
		//@  Other MyForm initialization code here.		
	}	
	
	private void initializeMyForm()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		text = "blogsort";
		clientSize = dfl.all.Size(1300, 720);
		//~DFL dfl.button.Button=btnBrowse
		btnBrowse = new dfl.button.Button();
		btnBrowse.name = "btnBrowse";
		btnBrowse.text = "Browse";
		btnBrowse.bounds = dfl.all.Rect(8, 8, 64, 24);
		btnBrowse.parent = this;
		//~DFL dfl.button.Button=btnSave
		btnSave = new dfl.button.Button();
		btnSave.name = "btnSave";
		btnSave.text = "Save";
		btnSave.bounds = dfl.all.Rect(700, 8, 64, 24);
		btnSave.parent = this;
		//~DFL dfl.textbox.TextBox=txtOutFile
		txtOutFile = new dfl.textbox.TextBox();
		txtOutFile.name = "txtOutFile";
		txtOutFile.text = "e:\\zhzm\\out01.jpg";
		txtOutFile.bounds = dfl.all.Rect(128, 8, 280, 24);
		txtOutFile.parent = this;
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.text = "Out:";
		label1.textAlign = dfl.all.ContentAlignment.MIDDLE_RIGHT;
		label1.bounds = dfl.all.Rect(88, 8, 36, 23);
		label1.parent = this;
		//~DFL dfl.label.Label=label2
		label2 = new dfl.label.Label();
		label2.name = "label2";
		label2.text = "max size:";
		label2.textAlign = dfl.all.ContentAlignment.MIDDLE_RIGHT;
		label2.bounds = dfl.all.Rect(440, 8, 52, 23);
		label2.parent = this;
		//~DFL dfl.textbox.TextBox=txtWidth
		txtWidth = new dfl.textbox.TextBox();
		txtWidth.name = "txtWidth";
		txtWidth.text = "1200";
		txtWidth.bounds = dfl.all.Rect(496, 8, 48, 23);
		txtWidth.parent = this;
		//~DFL dfl.label.Label=label3
		label3 = new dfl.label.Label();
		label3.name = "label3";
		label3.text = "x";
		label3.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label3.bounds = dfl.all.Rect(552, 8, 12, 23);
		label3.parent = this;
		//~DFL dfl.textbox.TextBox=txtHeight
		txtHeight = new dfl.textbox.TextBox();
		txtHeight.name = "txtHeight";
		txtHeight.text = "900";
		txtHeight.bounds = dfl.all.Rect(576, 8, 48, 23);
		txtHeight.parent = this;
		//~DFL dfl.listbox.ListBox=lbxFiles
		lbxFiles = new dfl.listbox.ListBox();
		lbxFiles.name = "lbxFiles";
		lbxFiles.bounds = dfl.all.Rect(8, 40, 182, 662);
		lbxFiles.parent = this;
		//~DFL dfl.picturebox.PictureBox=picBox
		picBox = new dfl.picturebox.PictureBox();
		picBox.name = "picBox";
		picBox.bounds = dfl.all.Rect(196, 40, 1100, 670);
		picBox.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.

		btnBrowse.click ~= &onBrowse;
		btnSave.click ~= &onSave;
		picBox.sizeMode = PictureBoxSizeMode.STRETCH_IMAGE;
		lbxFiles.drawMode = DrawMode.OWNER_DRAW_FIXED;
		lbxFiles.drawItem ~= &drawItem;
		lbxFiles.itemHeight = 130;

		closed ~= &OnClose;
	}

	private void onBrowse(Control sender, EventArgs ea)
	{
		auto ofd = new OpenFileDialog;
		ofd.title = "Open Image";
		ofd.filter = "All Image Files|*.bmp;*.ico;*.gif;*.jpg;*.jpeg|Bitmap Files|*.bmp|Icon Files|*.ico|JPEG Files|*.jpg;*.jpeg|All Files|*.*";
		imgProc.Start();
		if(DialogResult.OK == ofd.showDialog())
		{
			auto i = ofd.fileName.lastIndexOf('\\');
			bool[string] picext;
			foreach(ext; ["jpg", "bmp", "gif"]) picext[ext] = true;
			curPic = new Picture(ofd.fileName);
			picBox.image = curPic;
			lbxFiles.beginUpdate();
			lbxFiles.items.clear();
			foreach(string name; dirEntries(ofd.fileName[0..i], SpanMode.shallow)) {
				if (name.isFile && name[$-3..$].toLower() in picext)
					lbxFiles.items.add(new FileItem(name));
			}
			lbxFiles.endUpdate();
		}
	}

	private void onSave(Control sender, EventArgs ea)
	{
		if (curPic is null) return;
		Bitmap bmp = curPic.toBitmap();
		jpgWriter.Write(bmp, "pic.jpg");
		msgBox("ok");
	}

	private void drawItem(Object sender, DrawItemEventArgs ea)
	{
		ea.drawBackground();
		//ea.graphics.drawIcon(f.icon, ea.bounds.x + 2, ea.bounds.y + 2);

		FileItem it = cast(FileItem)lbxFiles.items[ea.index];
		Bitmap bmp = imgProc.GetThumb(it.fullname);
		if (bmp) {
			int w = bmp.width, h = bmp.height;
			bmp.draw(ea.graphics, Point(ea.bounds.x + 80-w/2, ea.bounds.y + 65-h/2));
		}

		ea.graphics.drawText(lbxFiles.items[ea.index].toString(), ea.font, ea.foreColor,
							 Rect(ea.bounds.x + 10, ea.bounds.y + 10, ea.bounds.width - 10, 20));
		ea.drawFocusRectangle();
	};

	void OnClose(Form f, EventArgs ea)
	{
		imgProc.Stop();
	}

	void onGotThumb()
	{
		lbxFiles.invalidate(true);
	}

	Picture curPic;
	JpegWriter jpgWriter;
	ImageProcessor imgProc;
}


/*int main()
{
	int result = 0;
	
	try
	{
		Application.enableVisualStyles();
		
		//@  Other application initialization code here.
		
		Application.run(new MyForm());
	}
	catch(Object o)
	{
		msgBox(o.toString(), "Fatal Error", MsgBoxButtons.OK, MsgBoxIcon.ERROR);
		
		result = 1;
	}
	
	return result;
}
*/
